### ISSUE TITLE
Mod Crashes when placing Framed item. [1.19.2]

### ISSUE THREAD

**Issue by acanthii** [LoremVIpsum/OpenSimpleFrames#1]
Minecraft 1.19.2
Fabric Loader 0.14.13
Mods Installed: Fabric API, OpenSimpleFrames (adding sodium and indium still has the same crash.)

Log: https://pastebin.com/EkDcy750

**Comment by LoremVIpsum** [comment]
I seem to be unable to recreate this error. does it occur on placing stairs? what exact process from world creations do you have to go about to make this occur?

**Comment by LoremVIpsum** [comment]
I have come up with a potential solution, please instead use version 1.0.1 located here https://github.com/LoremVIpsum/OpenSimpleFrames/releases/tag/dev I have a feeling it may fix your issue, then I will push it to modrinth

**Comment by acanthii** [comment]
That worked after I cleared my instance folder, thanks!
