### ISSUE TITLE
Some blocks have missing loot tables

### ISSUE THREAD

**Issue by Nataly171** [LoremVIpsum/OpenSimpleFrames#10]
The following blocks don't drop when you break them, and in fact have no loot tables at all:
- Framed Big Block
- Framed Huge Block
- Framed Chest
- Framed Up-Extended Block
- Framed Down-Extended Block
- Framed Door
- Framed Fence

**Comment by LoremVIpsum** [comment]
yup. sorry I didnt notice this earlier. will add them in when i have time
