### ISSUE TITLE
Vertical slabs?

### ISSUE THREAD

**Issue by WerySkok** [LoremVIpsum/OpenSimpleFrames#12]

**Comment by LoremVIpsum** [comment]
there is similar things here but yeah there arent any currently. see #11

**Comment by LoremVIpsum** [comment]
(trying to reduce the amount of issues, I don't know when I will add more frames yet but vertical slabs are definitely up there, in fact I believe these will be added in a merge soon)

**Comment by WerySkok** [comment]
You could set up a setting to that PR so that this issue would be closed once PR is merged
