### ISSUE TITLE
Repo out of date

### ISSUE THREAD

**Issue by WerySkok** [LoremVIpsum/OpenSimpleFrames#13]
Latest commit (https://github.com/LoremVIpsum/OpenSimpleFrames/commit/099f3a3c28aee4e4d73c628b3aa2980d5ec4f3ba) was on January 29 but 7 new versions came out after this date on Modrinth. It would be useful to update this repo so the progress will be more visible

**Comment by LoremVIpsum** [comment]
yeah I should probably fix that - there hasnt been many changes I basically just moved some lists around
