### ISSUE TITLE
chest nor door works

### ISSUE THREAD

**Issue by Corey3895432** [LoremVIpsum/OpenSimpleFrames#14]
:(

**Comment by Corey3895432** [comment]
they cannot be textured, why

**Comment by LoremVIpsum** [comment]
shift right click them or left click them with a block in hand

**Comment by MaiaMinecraft** [comment]
It doesn't work

**Comment by LoremVIpsum** [comment]
I imagine I have broken something at some point then (that's what it's meant to do when you do that) what version of Minecraft and what version of the mod are you using?

**Comment by MaiaMinecraft** [comment]
I think the 1.0.7 or something for the 1.19.2 (the last one for that
version?)

**Comment by MaiaMinecraft** [comment]
I think it's 1.0.2

**Comment by LoremVIpsum** [comment]
Just got a test world open, in survival mode you can start to break the chest or door with a valid framable block and that will do the trick :)

**Comment by MaiaMinecraft** [comment]
OK Thx do I need to download anything or it works with that version?

**Comment by LoremVIpsum** [comment]
nope, should work if your using one of the newer versions

**Comment by Corey3895432** [comment]
Im sorry, who are you? Is this a wrong adrees Sent from Mail for Windows From: LoremVSent: Friday, 11 August 2023 9:39 PMTo: LoremVIpsum/OpenSimpleFramesCc: Corey3895432; AuthorSubject: Re: [LoremVIpsum/OpenSimpleFrames] chest nor door works (Issue #14) nope, should work if your using one of the newer versions—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ajaxnotmeta** [comment]
what the hell is going on?

> Im sorry, who are you? Is this a wrong adrees Sent from Mail for Windows From: LoremVSent: Friday, 11 August 2023 9:39 PMTo: LoremVIpsum/OpenSimpleFramesCc: Corey3895432; AuthorSubject: Re: [LoremVIpsum/OpenSimpleFrames] chest nor door works (Issue #14) nope, should work if your using one of the newer versions—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by LoremVIpsum** [comment]
Looks like GitHub is messing up? I haven't been able to get working on this recently as things have started back up again

**Comment by LoremVIpsum** [comment]
I'm fairly sure this works in the latest version I published on modrinth but it might not work for the specific Minecraft version you are on

**Comment by LoremVIpsum** [comment]
Re-looking at this chain it'd seem there is some confusion between people responding using GitHub or by email - I'm going to close this issue but if it still persists on a version of Minecraft, please reopen it with the Minecraft version that is being used and the mod version being used, :)
