### ISSUE TITLE
black square bug

### ISSUE THREAD

**Issue by lostopkk** [LoremVIpsum/OpenSimpleFrames#15]
![image](https://github.com/LoremVIpsum/OpenSimpleFrames/assets/50776714/38ed9024-1a53-40b9-9afc-c5f968e46e23)
![image](https://github.com/LoremVIpsum/OpenSimpleFrames/assets/50776714/b0500fe5-8b83-4ddc-ac6a-cc56e000e147)

**Comment by LoremVIpsum** [comment]
this is somewhate intentional since the frames are based of trapdoors very closely, this way there are more distinguishable.
