### ISSUE TITLE
Scorchia/Deepslate bug

### ISSUE THREAD

**Issue by dhasial** [LoremVIpsum/OpenSimpleFrames#16]
I first placed cut deepslate on a framed ramp. I removed the block and later placed another framed ramp elsewhere, and tried to place cut scorchia (from create) on this new block. The texture that was placed was the same as cut deepslate which belonged to the first block, not the block in my hand.

I believe this is likely because Create's scorchia and scoria blocks are considered variants of deepslate and are thus being given the same IDs.

**Comment by LoremVIpsum** [comment]
you can reset the ids with /simpleframes command. it does take the block in your hands texture - this may be a known bug where the texture list is a tad broken

**Comment by LoremVIpsum** [comment]
also make sure you are using the newest version because I rearranged some of the lists so it should be more consistent

**Comment by dhasial** [comment]
It's definitely no longer crashing now, thanks for your work mate!
