### ISSUE TITLE
update repo so i can add stuff

### ISSUE THREAD

**Issue by sgogolowski** [LoremVIpsum/OpenSimpleFrames#17]
Hi can you update the repo? I would like to help and add vertical slabs. I pulled your repo but it is using fabric 1.18 and I want to build for 1.19. Also I would like the update to date repo in general. Thanks

**Comment by LoremVIpsum** [comment]
yup on it, for some reason my git setup is broken and I havent been able to fix it, but I can upload all the most recent versions of each mc version now

**Comment by LoremVIpsum** [comment]
I believe each version is now up to date. sorry about this - if you think your missing files Ill keep this chain open, at least from your blank copy you *should* be able to do proper version control 🤣

**Comment by sgogolowski** [comment]
WOOOOOOOOOOOOOOO!!! IM HYPE! I will clone this repo and add the code I have for vertical slabs later. Thanks a lot

**Comment by LoremVIpsum** [comment]
now that im at it, ive started updating the wiki to help with future ideas for frames :)
