### ISSUE TITLE
Crash when placing a framed door next to a framed fence

### ISSUE THREAD

**Issue by thehobojoe** [LoremVIpsum/OpenSimpleFrames#2]
```
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{simpleframes:framed_door}, it is not an allowed value
```
I've tried a few other combinations of blocks with fences and doors, so far this is the only broken interaction I've run into.

**Comment by LoremVIpsum** [comment]
the door was a full block, it is no longer, please try the version in the releases here on github (1.0.2) https://github.com/LoremVIpsum/OpenSimpleFrames/releases/tag/dev2

**Comment by LoremVIpsum** [comment]
please reopen the issue if you believe this bug has persisted
