### ISSUE TITLE
[Bug/Optimisation] slow startup with many block variants

### ISSUE THREAD

**Issue by AlienXtream** [LoremVIpsum/OpenSimpleFrames#22]
seems there is a significant slowdown of loading/startup of the game when large numbers of blocks are present in the pack (things like "Chipped" and "Chisel" that add many new building blocks). i am unsure if this is something you can fix or not but if you are able to verify and fix this it'd be great. totally understandable if you cant as its not gamebreaking. im used to slow load times from forge so this is still faster than that XD

**Comment by LoremVIpsum** [comment]
This is not a problem with open simple frames, the amount of blockstates I have never goes up all the states present are present in every version based of the config, I dont think OSF drastically slows the game in that way, or at least, only by a set amount if it does, is it specfically OSF you have isolated to be causing lag?

**Comment by AlienXtream** [comment]
it is as far as i can tell it is OSF. i assume its just janky minecraft being janky. i also admit i didn't do an objectively rigerous test and simply compared it between my pack and a standalone instance as a "control". i can do more testing at a later time if you like, unless you are able to recreate the "issue" yourself. it seems to be all happening in the "pre launch" stage (after pressing play/launch but before the minecraft window pops up) on prism launcher so its also possible its doing something extra/different.

**Comment by LoremVIpsum** [comment]
basically OSF has a set number of blockstates - this never changes theoretically, the idea is there are 100 texture states and blocks are assigned to those texture states as needed, there should be no problem with other mods as OSF only cares on right or left clicking - sorry for the long time to respond, Im going to close this issue for the time being, but if you do end up doing some testing, please let me know!
