### ISSUE TITLE
[Bug] 1.20.1 Textures change to last used after relogging

### ISSUE THREAD

**Issue by Semorphim** [LoremVIpsum/OpenSimpleFrames#25]
When I placed framed Stairs with oak planks as texture and use framed stairs with spruce logs in a different location both textures change to the last used (in this case spruce logs) after rejoining my multiplayer server.

**Comment by LoremVIpsum** [comment]
this is to do with how many textures are presently being used in the world, theoretically this was fixed in the newer version, but which version are you using?

**Comment by Semorphim** [comment]
Currently running version 1.1.0 for Fabric 1.20.1

After Rebooting the server it seems to be fixed for now. Thank you for your Reply :D
