### ISSUE TITLE
[1.19.4] [fabric] game fails to launch with no other mods installed: exit code -1

### ISSUE THREAD

**Issue by BigClarky** [LoremVIpsum/OpenSimpleFrames#29]
mod list: 
Open Simple Frames
Fabric Api

crash log: 
https://mclo.gs/mV7FLr7

**Comment by LoremVIpsum** [comment]
this looks like the fabric loader your using is newer than the one I built it with, saying that something doesnt exist any more, if you can use an older version of fabric please do so, otherwise ill rebuild it the next time I get time

**Comment by BigClarky** [comment]
I haven't been able to find a fabric version that works

**Comment by LoremVIpsum** [comment]
I think you found this on #27 so I will close this now
