### ISSUE TITLE
using Mod on a server eventually results in blocks becoming invisible.

### ISSUE THREAD

**Issue by ghost** [LoremVIpsum/OpenSimpleFrames#34]
I had the issue with a server that was modded. The entities like chests and stuff still worked. but after about a week or two of just running the mod on a server the blocks existed but had weird rendering. Things like stairs would look like half slabs, but still allow you to walk up them as if they were stairs. One time I logged on and all the blocks had disappeared. Ended up uninstalling the mod.

**Comment by LoremVIpsum** [comment]
I think this is the same as #26 so I'm going to close this for now, just so I know what is what - if you think it is different, reopen it
