### ISSUE TITLE
Mixin crashes on 1.20.2+ but marked supporting 1.20.1+

### ISSUE THREAD

**Issue by Linguardium** [LoremVIpsum/OpenSimpleFrames#39]
https://github.com/LoremVIpsum/OpenSimpleFrames/blob/f072937c4715ccd722aa1cba1c2341e8cb93084f/src/main/java/com/loremv/simpleframes/mixin/PlayerManagerMixin.java#L27

https://modrinth.com/mod/open-simple-frames/version/1.2.0 marked as supporting 1.20.2, 1.20.3, and 1.20.4

**Comment by SinkWashy** [comment]
Confirmed in 1.20.4

https://mclo.gs/vX4H2qZ

**Comment by LoremVIpsum** [comment]
huh ok, at least this should be an easy enough fix with the time I have currently

**Comment by LoremVIpsum** [comment]
new version now works on 1.20.4, and probably the versions before it that aren't 1.20.1
