### ISSUE TITLE
Crash when trying to place down framed stair. 

### ISSUE THREAD

**Issue by CoolGuyGit** [LoremVIpsum/OpenSimpleFrames#4]
Whenever I try to place down a framed stair the game instantly crashes.  My crash file should be attached here.  The only mods that I have installed are Fabric Api and Open Simple Frames.

[crash-2023-01-31_18.30.16-client.txt](https://github.com/LoremVIpsum/OpenSimpleFrames/files/10552124/crash-2023-01-31_18.30.16-client.txt)

**Comment by LoremVIpsum** [comment]
oh boy, yeah I forgot to fully port a change from the 1.19 version please go and download 1.0.2c https://modrinth.com/mod/open-simple-frames/version/1.0.2c im about 99% sure that should fix your issue

**Comment by LoremVIpsum** [comment]
please reopen the issue if you believe this bug has persisted
