### ISSUE TITLE
Right-clicking a frame with a block will place the block while setting the texture

### ISSUE THREAD

**Issue by thehobojoe** [LoremVIpsum/OpenSimpleFrames#5]
Happens with the majority of frames in the mod (h-frame fences are a notable exception). Interactable frames like doors and chests cannot have their texture set at all because they are opened by the click, and the block is placed as well.

https://user-images.githubusercontent.com/3493638/219906252-2d5e3b4c-430e-462e-80eb-b0352e53e1ed.mp4

**Comment by LoremVIpsum** [comment]
you can apply textures by left clicking on any of the frames, but yeah, it should probably do one or the other

**Comment by LoremVIpsum** [comment]
actually, if you sneak right click, it should work.
